#19: Remove Lombok
exasol/error-code-model-java pull request #20
Opened 2022-08-01 13:29 UTC by redcatbear

Closes #19.

2022-08-01 14:01 UTC, kaklakariada requested changes

2022-08-01 14:01 UTC, kaklakariada commented on src/main/java/com/exsol/errorcodemodel/ErrorCodeReport.java
> +        if (this == other) return true;
Please check if there is a EqualsVerifyer-test for ErrorCodeReport

2022-08-01 14:01 UTC, kaklakariada commented on src/main/java/com/exsol/errorcodemodel/ErrorIdentifier.java
> +     * @param type type of error (warning, error, fatal)
```suggestion
     * @param type type of error
```
This is an enum. Is it necessary to list the options here?

2022-08-01 14:01 UTC, kaklakariada commented on src/main/java/com/exsol/errorcodemodel/ErrorIdentifier.java
> +    public boolean equals(final Object other) {
Please check if there is a EqualsVerifyer-test for ErrorIdentifier

2022-08-01 14:01 UTC, kaklakariada commented on src/main/java/com/exsol/errorcodemodel/ErrorMessageDeclaration.java
> + * This class represents an error message declaration as you would find it in the Java code.
👍

2022-08-01 14:01 UTC, kaklakariada commented on src/main/java/com/exsol/errorcodemodel/ErrorMessageDeclaration.java
> +    private static final int NO_SOURCE_LINE = -1;
👍

2022-08-01 14:01 UTC, kaklakariada commented on src/main/java/com/exsol/errorcodemodel/ErrorMessageDeclaration.java
> +    public boolean equals(final Object other) {
Please check if there is a EqualsVerifyer-test for ErrorMessageDeclaration

2022-08-01 14:01 UTC, kaklakariada commented on src/main/java/com/exsol/errorcodemodel/NamedParameter.java
> +    public boolean equals(final Object other) {
Please check if there is a EqualsVerifyer-test for NamedParameter

2022-08-02 05:05 UTC, redcatbear commented on src/main/java/com/exsol/errorcodemodel/ErrorIdentifier.java
> +     * @param type type of error (warning, error, fatal)
Since `type` was chosen as name, that is not very self explaining. That's why I put in examples.

2022-08-02 05:06 UTC, redcatbear commented on src/main/java/com/exsol/errorcodemodel/ErrorCodeReport.java
> +        if (this == other) return true;
Done.

2022-08-02 06:29 UTC, kaklakariada approved these changes

2022-08-02 06:31 UTC, merged